# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         MMS-Mail-Provider-UKVirgin
version:      0.02
version_from: lib/MMS/Mail/Provider/UKVirgin.pm
installdirs:  site
requires:
    MMS::Mail::Message::Parsed:    0
    MMS::Mail::Provider:           0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
